### ISSUE TITLE
Add Changlog

### ISSUE THREAD

**Issue by madanyang** [karthink/gptel#874]
First thanks for the great package, I am really enjoying using it, and I am sure I haven't been utilizing it to its full capacity.

It would be great if you can add a CHANGELOG.md to the project.

It would help for those like me to see what are the changes, fixes in the code. As you most probably know that this can be done automatically, so setting up and configuring once should be sufficient to create and update this file.

Thanks for your amazing work.

**Comment by madanyang** [comment]
No, CHANGELOG would be generated by when the repo is updated with your git commits/pushes reflecting what changed. It is git log in a markdown format enabling to see what changed what fixed. Your last commit is circa 2 hrs ago but NEWS is like a week old. CHANGELOG is uptodate

**Comment by karthink** [comment]
I see, I didn't know.  A CHANGELOG sounds like a good idea then.

gptel follows the GNU-style "file-oriented" commit heading format, for example:

```
gptel-anthropic: Add support for claude-3-7-sonnet-20250219
```

This is different from the conventional commits standard (`<feat>: ...`) typically used for auto-categorization of commits.

Any recommendations for auto-generating a CHANGELOG for gptel?

**Comment by madanyang** [comment]
@karthink there are many github actions, yet it depends on your personal preferences and choices and at the end how you want to automate things. So I guess my best recommendation would be have a search and find to your liking

**Comment by karthink** [comment]
I tried to use `auto-changelog` and `git-cliff`, and neither of them could generate a meaningful changelog for the GNU project  commit format I use for gptel.

I spent a couple of hours trying to configure them to do so, but I can't figure it out.  If you can get them to do so it will help. 

BTW, I don't understand what you get from a changelog that you wouldn't from just looking at the commit messages.  I write very detailed commit messages, often with motivation and examples.  Example: 31c9ee3ae0ad390863d3c5bdb855e12de286e349

**Comment by ultronozm** [comment]
@karthink I don't know if the following produces the format desired by @madanyang, but if you haven't already, try the following in the `gptel` source directory, assuming Emacs source is in "~/gnu-emacs":

```sh
~/gnu-emacs/build-aux/gitlog-to-changelog > ChangeLog
```

**Comment by madanyang** [comment]
> I tried to use `auto-changelog` and `git-cliff`, and neither of them could generate a meaningful changelog for the GNU project commit format I use for gptel.
> 
> I spent a couple of hours trying to configure them to do so, but I can't figure it out. If you can get them to do so it will help.

Will do 


> BTW, I don't understand what you get from a changelog that you wouldn't from just looking at the commit messages. I write very detailed commit messages, often with motivation and examples. Example: [31c9ee3](https://github.com/karthink/gptel/commit/31c9ee3ae0ad390863d3c5bdb855e12de286e349)

Rather than going commit by commit to see what changed/fixed/added changelog provides a simple interface. If you just updated the README.org or just comments in the code that means I don't  have to update the package and just reading the Changelog will tell me exactly that.

**Comment by madanyang** [comment]
The following is  a work of of gptel and claude sonnet. You may need to adjust it to your needs but it should be a better option compared to the others you have tried.  Hope it helps. 

```markdown
# GNU-Style Changelog Generator

This project uses automated changelog generation specifically designed for GNU-style file-oriented commit messages, as used in projects like [gptel](https://github.com/karthink/gptel).

## Overview

Unlike conventional commit formats (feat:, fix:, etc.), GNU-style commits follow a file-oriented approach:

```
filename.ext: Brief description of change
filename1.ext, filename2.ext: Brief description affecting multiple files
```

This changelog generator is optimized to parse and format these commit messages properly.

## How It Works

The changelog generation uses three key components:

### 1. Configuration (.chglog/config.yml)

```yaml
tag:
  prefix: "v"          # Matches tags like v1.0.0, v0.2.1, etc.
  sort: semver         # Sort tags by semantic versioning
  filter:
    pattern: "^v"      # Only consider tags starting with 'v'

changelog:
  header: |
    # Changelog for gptel

  sections:
    - title: "Changes"
      regex: '^[[:alnum:], _./+-]+:'   # Matches GNU-style file-oriented commit subjects
      teardown: true
```

**Key improvements over generic tools:**
- Regex specifically targets GNU-style format: `filename.ext: description`
- Supports multiple files: `file1.ext, file2.ext: description`
- Filters out non-conforming commits

### 2. Template (CHANGELOG.tpl.md)

```jinja
{{ .Changelog.Header }}

{{ range .Versions }}
## {{ if .Tag }}{{ .Tag }}{{ else }}Unreleased{{ end }} — {{ .Date }}

{{- range .Commits }}
- {{ .Subject }}
{{- end }}

{{ end }}
```

**Features:**
- Clean, minimal format focused on commit subjects
- Proper version grouping with dates
- Maintains original GNU-style commit format

### 3. GitHub Workflow (changelog.yml)

```yaml
name: Generate GNU-Style Changelog

on:
  push:
    tags:
      - 'v*'             # Trigger on every new version tag push
  workflow_dispatch:     # Also allow manual trigger

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Changelog
        uses: pfandie/generate-changelog-action@v1.0.9
        with:
          config: .chglog/config.yml
          template: CHANGELOG.tpl.md
          output: CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git diff --quiet || git commit -m "chore: update CHANGELOG for $GITHUB_REF"
          git push
```

## Setup Instructions

1. **Copy the configuration files to your repository:**
   ```bash
   mkdir -p .chglog
   cp .chglog/config.yml your-repo/.chglog/
   cp CHANGELOG.tpl.md your-repo/
   cp changelog.yml your-repo/.github/workflows/
   ```

2. **Ensure your commit messages follow GNU-style format:**
   ```bash
   # Good examples:
   git commit -m "gptel.el: Add new backend support"
   git commit -m "README.md, INSTALL.md: Update installation instructions"
   git commit -m "test-gptel.el: Fix failing authentication tests"
   
   # Avoid:
   git commit -m "feat: add new backend support"  # conventional commits
   git commit -m "fix authentication bug"         # no file reference
   ```

3. **Use semantic version tags:**
   ```bash
   git tag v1.0.0
   git push origin v1.0.0
   ```

## Generated Changelog Format

The generated CHANGELOG.md will look like:

```markdown
# Changelog for gptel

## v1.2.0 — 2024-01-15

- gptel.el: Add support for Claude 3.5 Sonnet
- gptel-anthropic.el: Improve error handling for rate limits  
- README.md: Update API key configuration examples
- test-gptel.el: Add tests for new Anthropic models

## v1.1.0 — 2023-12-20

- gptel.el: Add streaming response support
- gptel-openai.el: Fix timeout handling
- CHANGELOG.md: Add release notes for v1.1.0
```

## Benefits Over Generic Tools

1. **GNU-Style Awareness**: Specifically designed for file-oriented commits
2. **Proper Filtering**: Only includes commits that follow the expected format
3. **Clean Output**: Maintains the original commit message clarity
4. **Version Grouping**: Automatically groups changes by release tags
5. **Automated**: Runs on every tag push, no manual intervention needed

## Troubleshooting

### Common Issues

**Q: Changelog is empty or missing commits**
A: Check that your commits follow the GNU-style format: `filename.ext: description`

**Q: Non-GNU commits appear in changelog**
A: The regex filter should catch this, but you may need to adjust the pattern in `.chglog/config.yml`

**Q: Workflow fails to push**
A: Ensure the GitHub token has write permissions to the repository

### Validation

To check if your commits follow GNU-style format:
```bash
git log --oneline --grep="^[[:alnum:], _./+-]*:"
```

This will show commits that match the expected pattern.

## Comparison with Other Tools

| Tool | GNU-Style Support | File-Oriented | Auto-Generation |
|------|------------------|---------------|-----------------|
| auto-changelog | ❌ Generic | ❌ No | ✅ Yes |
| git-cliff | ⚠️ Limited | ⚠️ Partial | ✅ Yes |
| **This Solution** | ✅ Full | ✅ Yes | ✅ Yes |

## License

This configuration is provided as-is for GNU-style projects. Modify as needed for your specific requirements.
```
